describe('Create a new Goal', () => {
  beforeEach(() => {
    cy.createSentencePlan().then(planDetails => {
      cy.wrap(planDetails).as('planDetails')
      cy.openSentencePlan(planDetails.oasysAssessmentPk)
      cy.visit('/about-pop')
    })
  })

  it('Creates a new goal with steps', () => {
    cy.get("a[href='/create-goal/accommodation']").click()
    cy.url().should('include', '/create-goal/accommodation')
    cy.get('#goal-input-autocomplete').type('acc{downArrow},{enter}')
    cy.get('#other-area-of-need-radio').click()
    cy.get('.govuk-checkboxes').first().contains('Employment and education').click()
    cy.get('.govuk-checkboxes').first().contains('Drug use').click()
    cy.get('#start-working-goal-radio').click()
    cy.get('.govuk-radios').last().contains('In 6 months').click()
    cy.get('button').contains('Add steps').click()
    cy.url().should('include', '/steps/create')
    cy.get('#step-input-autocomplete').click()
    cy.get('#step-input-autocomplete').type('This is the first step')
    cy.get('#actor').click()
    cy.get('#actor-2').click()
    cy.get('button').contains('Save and continue').click()
    cy.url().should('include', '/plan-summary')
  })

  it('Creates a new goal with errors', () => {
    cy.get("a[href='/create-goal/accommodation']").click()
    cy.url().should('include', '/create-goal/accommodation')
    cy.get('#goal-input-autocomplete').type('acc{downArrow},{enter}')
    cy.get('#start-working-goal-radio').click()
    cy.get('.govuk-radios').last().contains('In 6 months').click()
    cy.get('button').contains('Add steps').click()
    cy.url().should('include', '/create-goal/accommodation')
    cy.contains('#other-area-of-need-radio-error', 'Select yes if this goal is related to any other area of need')
  })

  it('Creates a new goal without steps', () => {
    cy.get("a[href='/create-goal/accommodation']").click()
    cy.url().should('include', '/create-goal/accommodation')
    cy.get('#goal-input-autocomplete').type('acc{downArrow},{enter}')
    cy.get('#other-area-of-need-radio').click()
    cy.get('.govuk-checkboxes').first().contains('Employment and education').click()
    cy.get('.govuk-checkboxes').first().contains('Drug use').click()
    cy.get('#start-working-goal-radio').click()
    cy.get('.govuk-radios').last().contains('In 6 months').click()
    cy.get('button').contains('Save without steps').click()
    cy.url().should('include', '/plan-summary')
  })
})
