export default {
  ABOUT_POP: '/about-pop',
  CREATE_GOAL: '/create-goal/:areaOfNeed',
  ADD_STEPS: '/goal/:uuid/add-steps',
  PLAN_OVERVIEW: '/plan',
  VIEW_ACHIEVED_GOAL: '/view-achieved-goal/:uuid',
  VIEW_REMOVED_GOAL: '/view-removed-goal/:uuid',
  GOALS: '/goals',
  GOALS_ORDER: '/goals/:type/:uuid/:operation',
  REMOVE_GOAL: '/remove-goal/:uuid',
  DELETE_GOAL: '/confirm-delete-goal/:uuid',
  UPDATE_GOAL: '/update-goal/:uuid',
  CHANGE_GOAL: '/change-goal/:uuid',
  ACHIEVE_GOAL: '/confirm-achieved-goal/:uuid',
  AGREE_PLAN: '/agree-plan',
  PLAN_HISTORY: '/plan-history',
}
