services:
  ui:
    image: quay.io/hmpps/hmpps-sentence-plan-ui:local
    build:
      target: development
    command: npm run start:dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ../:/app:cached
      - node_modules:/app/node_modules

  hmpps-auth:
    environment:
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0"

volumes:
  node_modules:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_node_modules
