services:
  ui:
    environment:
      HMPPS_ARNS_HANDOVER_EXTERNAL_URL: http://arns-handover:7070
      INGRESS_URL: http://ui:3000

  oastub:
    environment:
      INGRESS_URL: http://oastub:3000

  arns-handover:
    environment:
      CLIENT_SP_OAUTH_REDIRECT_URI: http://ui:3000/sign-in/callback
      CLIENT_SP_HANDOVER_REDIRECT_URI: http://ui:3000/sign-in
      HMPPS_HANDOVER_EXTERNAL_URL: http://arns-handover:7070
      OASYS_BASE_URL: http://oastub:3000
      OASYS_RETURN_URLS: http://oastub:3000

  playwright:
    image: mcr.microsoft.com/playwright:v1.49.1-noble
    environment:
      BASE_URL: http://ui:3000
      ARNS_HANDOVER_URL: http://arns-handover:7070
      HMPPS_AUTH_URL: http://hmpps-auth:9090
      SP_API_URL: http://api:8080
      OASTUB_URL: http://oastub:3000
      COORDINATOR_API_URL: http://coordinator-api:8080
    volumes:
      - ../:/playwright-tests
    working_dir: /playwright-tests

volumes:
  test_results:
