---
# Per environment values which override defaults in hmpps-sentence-plan-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-sentence-plan-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-sentence-plan-ui.hmpps.service.justice.gov.uk"
    SENTENCE_PLAN_API_URL: "https://sentence-plan-api.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    HMPPS_ARNS_HANDOVER_URL: "https://arns-handover-service.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: hmpps-sentence-plan-notifications
