---
# Per environment values which override defaults in hmpps-sentence-plan-ui/values.yaml

generic-service:
  nameOverride: $RELEASE_NAME
  replicaCount: 1

  ingress:
    host: pr-$PR_NUMBER.sentence-plan-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://pr-$PR_NUMBER.sentence-plan-dev.hmpps.service.justice.gov.uk"
    SENTENCE_PLAN_API_URL: "https://sentence-plan-api-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_ARNS_HANDOVER_URL: "https://arns-handover-service-dev.hmpps.service.justice.gov.uk"
    HMPPS_ARNS_API_URL: "https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    COORDINATOR_API_URL: "https://arns-coordinator-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    DEPLOYMENT_NAME: PR-$PR_NUMBER
    ENVIRONMENT_NAME: DEV

generic-prometheus-alerts:
  targetApplication: $RELEASE_NAME
  alertSeverity: hmpps-sentence-plan-notifications
