---
# Per environment values which override defaults in hmpps-sentence-plan-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: sentence-plan-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://sentence-plan-preprod.hmpps.service.justice.gov.uk"
    SENTENCE_PLAN_API_URL: "https://sentence-plan-api-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    HMPPS_ARNS_HANDOVER_URL: "https://arns-handover-service-preprod.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    COORDINATOR_API_URL: "https://arns-coordinator-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    DELIUS_API_BASE_URL: "https://sentence-plan-and-delius-preprod.hmpps.service.justice.gov.uk"
    MPOP_URL: "https://manage-people-on-probation-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    SAN_URL: "https://strengths-based-needs-assessments-preprod.hmpps.service.justice.gov.uk"

  namespace_secrets:
    hmpps-sentence-plan-ui-feedback-url:
      FEEDBACK_URL: "FEEDBACK_URL"

generic-prometheus-alerts:
  alertSeverity: hmpps-sentence-plan-notifications
