---
# Per environment values which override defaults in hmpps-sentence-plan-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: sentence-plan-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://sentence-plan-dev.hmpps.service.justice.gov.uk"
    SENTENCE_PLAN_API_URL: "https://sentence-plan-api-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_ARNS_HANDOVER_URL: "https://arns-handover-service-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    COORDINATOR_API_URL: "https://arns-coordinator-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

  namespace_secrets:
    hmpps-sentence-plan-ui-feedback-url:
      FEEDBACK_URL: "FEEDBACK_URL"

  allowlist:
    capita-dev: 51.104.16.30/31
    captia-further: 172.167.141.40/32
    neil-test: 51.155.102.238/32
    capita-developers-vms-one: 85.115.52.180/32
    capita-developers-vms-two: 85.115.52.200/29
    capita-developers-vms-three: 85.115.53.180/32
    capita-developers-vms-four: 85.115.53.200/29
    capita-developers-vms-five: 85.115.54.180/32
    capita-developers-vms-six: 85.115.54.200/29
    krupal-app-sec: 80.195.27.199/32

generic-prometheus-alerts:
  alertSeverity: hmpps-sentence-plan-notifications
