name: Production pipeline [build -> test -> deploy]

on:
  push:
    branches:
      - production

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  helm_lint:
    strategy:
      matrix:
        environments: [ 'dev', 'test', 'preprod', 'prod' ]
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}

  node_build:
    name: node build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_build.yml@v2
    secrets: inherit

  node_unit_tests:
    name: node unit tests
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_unit_tests.yml@v2
    needs: node_build
    secrets: inherit

  build_docker:
    name: Build docker image
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      tag_latest: false
      push: false
      load: true
      docker_multiplatform: false
      upload_image_artifact: true

  e2e_test:
    needs: [ build_docker ]
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1, 2, 3, 4, 5 ]
    uses: ./.github/workflows/e2e_test.yml
    with:
      app_version: ${{ needs.build_docker.outputs.app_version }}
      job-index: ${{ strategy.job-index }}
      job-total: ${{ strategy.job-total }}
      matrix-container: ${{ matrix.containers }}

  publish-test-results:
    name: "Publish Tests Results"
    needs: [ e2e_test, node_unit_tests ]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()

    steps:
      - name: Download Unit Test Artifacts
        uses: actions/download-artifact@v4
        with:
          path: unit_test_artifacts
          pattern: npm_unit_test_artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "unit_test_artifacts/**/*.xml"
          check_name: "Unit Test Results"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: test_results_*

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/*.xml"
          check_name: "Cypress Test Results"

  publish_docker:
    name: Publish docker image
    needs:
      - helm_lint
      - node_build
      - node_unit_tests
      - e2e_test
      - build_docker
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_push.yml@v2
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      app_version: ${{ needs.build_docker.outputs.app_version }}
      tag_latest: true

  deploy_test:
    name: Deploy to test environment
    needs:
      - build_docker
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'test'
      app_version: '${{ needs.build_docker.outputs.app_version }}'

  deploy_preprod:
    name: Deploy to pre-production environment
    needs:
      - build_docker
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build_docker.outputs.app_version }}'

  deploy_prod:
    name: Deploy to production environment
    needs:
      - build_docker
      - deploy_preprod
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'prod'
      app_version: '${{ needs.build_docker.outputs.app_version }}'
