name: Parallel Cypress Tests

on:
  workflow_dispatch:
  push:
    branch:
      - test-cypress-split

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=4g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    name: Cypress run
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bring up environment
        run: |
          make test-up

      - name: Run split Cypress tests
        run: |
          make e2e-ci
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            /integration_tests/integration_tests/screenshots/**/*.png
