name: Run visual regression snapshot tests

on:
  workflow_call:
    inputs:
      app_version:
        description: App version
        required: true
        type: string
      job-index:
        description: 'The index of the current job in the matrix'
        required: false
        type: number
        default: 1
      job-total:
        description: 'The total number of jobs in the matrix'
        required: false
        type: number
        default: 1
      matrix-container:
        description: 'The matrix container description'
        required: false
        type: number
        default: 1

jobs:
  visual_regression_test:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ inputs.app_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: build_image
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/build_image.tar

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Run npm ci
        run: npm ci

      - name: Stand up a test environment
        run: |
          make test-up

      - name: Run visual regression testing
        run: make vrt-ci
        env:
          SPLIT: ${{ inputs.job-total }}
          SPLIT_INDEX: ${{ inputs.job-index }}

      - name: Upload failed visual regression artifacts (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vrt-screenshots_${{ inputs.matrix-container }}
          path: 'cypress-image-diff-screenshots/comparison'
